Math optimizations
axmolengine/axmol pull request #2115
Opened 2024-08-28 17:27 UTC by smilediver

Mostly moves some trivial and commonly used methods in math classes to headers so that they can be inlined by compiler.

2024-08-29 14:56 UTC, paulocoutinhox commented
What is inl file?

2024-08-30 00:41 UTC, halx99 requested changes
**I prefer just implement inline APIs in class define directly, don't create individual .inl file if the inline APIs are public**

2024-08-30 00:41 UTC, halx99 commented on core/math/Color.inl
don't create individual .inl file

2024-08-30 00:42 UTC, halx99 commented on core/math/Mat4.inl
don't create individual .inl file

2024-08-30 00:42 UTC, halx99 commented on core/math/Rect.inl
don't create individual .inl file

2024-08-30 00:43 UTC, halx99 commented on core/math/Vec4.inl
don't create individual .inl file

2024-08-30 00:44 UTC, halx99 commented on core/math/Quaternion.inl
move to class define body

2024-08-30 10:26 UTC, smilediver commented
Should I put definitions with declarations like so:

```cpp
class Color {
    void method() { doStuff(); }
};
```
or keep declarations clean and put definitions at the end of file like this:
```cpp
class Color {
    void method();
};

void Color::method() { doStuff(); }
```

2024-08-30 11:03 UTC, halx99 commented
I prefer first one, shorten words

2024-09-05 00:57 UTC, halx99 approved these changes

2024-09-05 00:57 UTC, merged