DrawNode V2
axmolengine/axmol pull request #2124
Opened 2024-09-01 10:16 UTC by aismann

## Describe your changes

Add all review parts. 
Please review again. Thanks.

## Issue ticket number and link

## Checklist before requesting a review
### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [x] I have checked readme and add important infos to this PR.
- [x] I have added thorough tests.

2024-09-01 11:28 UTC, aismann commented
@smilediver, @halx99 
Please review again. Thanks.

2024-09-01 14:35 UTC, halx99 commented
the 2nd test of `Node:Draw` will crash on android devices, and follow test has flick problem on android devices:
![Screenshot_2024-09-01-22-33-11-177_org axmol cpp_tests](https://github.com/user-attachments/assets/07650408-7cda-485b-aacd-f0b67097d0f5)

2024-09-01 14:37 UTC, halx99 commented
just download cpp-test apk from this PR latest buile artifacts will reproduce above problems:

https://github.com/axmolengine/axmol/actions/runs/10653604025/artifacts/1879283194

2024-09-01 19:21 UTC, aismann commented
> just download cpp-test apk from this PR latest build artifacts will reproduce above problems:
> 
> https://github.com/axmolengine/axmol/actions/runs/10653604025/artifacts/1879283194

I think its the tester itself which be not stable.
I will look.

2024-09-02 00:10 UTC, halx99 commented
> the 2nd test of `Node:Draw` will crash on android devices, and follow test has flick problem on android devices: ![Screenshot_2024-09-01-22-33-11-177_org axmol cpp_tests](https://private-user-images.githubusercontent.com/6977319/363498845-07650408-7cda-485b-aacd-f0b67097d0f5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzYwODAsIm5iZiI6MTcyNTIzNTc4MCwicGF0aCI6Ii82OTc3MzE5LzM2MzQ5ODg0NS0wNzY1MDQwOC03Y2RhLTQ4NWItYWFjZC1mMGI2NzA5N2QwZjUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDAwOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWFjNzRiNWUxN2FmY2ZkZjMwNTA2NTAzYWJiYTQwN2ViZjA5NGE5OTViOGE1OGQ5NjNiYmExZGViMDBjMmI4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QtOycLK1KHHPiV0WXWFvJ6ZBWr4xg1z-8nl_Cxyey2g)

The original draw node works well

2024-09-02 05:48 UTC, aismann commented
@halx99 
Can you check the android issue again

2024-09-02 15:47 UTC, halx99 requested changes

2024-09-02 15:47 UTC, halx99 commented on tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
> +    labelRound = Label::createWithTTF("DrawNode::Round", "fonts/Arial.ttf", 12);
```suggestion
    labelRound = Label::createWithTTF("DrawNode::Round", "fonts/arial.ttf", 12);
```

2024-09-02 15:47 UTC, halx99 commented on tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
> +    labelSquare = Label::createWithTTF("DrawNode::Square", "fonts/Arial.ttf", 12);
```suggestion
    labelSquare = Label::createWithTTF("DrawNode::Square", "fonts/arial.ttf", 12);
```

2024-09-02 15:47 UTC, halx99 commented on tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
> +    labelButt = Label::createWithTTF("DrawNode::Butt", "fonts/Arial.ttf", 12);
```suggestion
    labelButt = Label::createWithTTF("DrawNode::Butt", "fonts/arial.ttf", 12);
```

2024-09-02 15:47 UTC, halx99 commented
Could you also preserve old DrawNodeTests?

2024-09-02 18:50 UTC, aismann commented
> Could you also preserve old DrawNodeTests?

Sure

2024-09-02 19:07 UTC, aismann commented on tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
> +    labelSquare = Label::createWithTTF("DrawNode::Square", "fonts/Arial.ttf", 12);
done

2024-09-02 19:07 UTC, aismann commented on tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
> +    labelRound = Label::createWithTTF("DrawNode::Round", "fonts/Arial.ttf", 12);
done

2024-09-03 00:21 UTC, halx99 commented
> > Could you also preserve old DrawNodeTests?
> 
> Sure. But the most be no longer usefull

I just want to see all old tests works well

2024-09-03 16:47 UTC, halx99 commented
This test seems dead loop on android device:
![Screenshot_2024-09-04-00-46-21-107_org axmol cpp_tests](https://github.com/user-attachments/assets/d479aa31-fb56-44a7-b9e4-d83da11b6efd)

2024-09-04 09:55 UTC, aismann commented
@halx99 
Can you test it again?
Here on my device its works well (used: build / android (armv7))

2024-09-04 11:45 UTC, halx99 commented
> This test seems dead loop on android device: ![Screenshot_2024-09-04-00-46-21-107_org axmol cpp_tests](https://private-user-images.githubusercontent.com/6977319/364069642-d479aa31-fb56-44a7-b9e4-d83da11b6efd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTA1NzUsIm5iZiI6MTcyNTQ1MDI3NSwicGF0aCI6Ii82OTc3MzE5LzM2NDA2OTY0Mi1kNDc5YWEzMS1mYjU2LTQ0YTctYjllNC1kODNkYTExYjZlZmQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMTE0NDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJkMTUyMzRiYWVmMmY4YzBmM2Q4NzkwMjhhZTMxMWViOTA0M2Y3MGFkYjRhYjJiYjQ4YTI1NWZiYjBhMWRmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hQwQPx4Dfts6luIT2WbVJCiNFO3TMr91RGu0Khr3SO4)

issue still exist, when I goto the test, I can't get any response when I click any button

2024-09-04 12:54 UTC, aismann commented
> > This test seems dead loop on android device: ![Screenshot_2024-09-04-00-46-21-107_org axmol cpp_tests](https://private-user-images.githubusercontent.com/6977319/364069642-d479aa31-fb56-44a7-b9e4-d83da11b6efd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTA1NzUsIm5iZiI6MTcyNTQ1MDI3NSwicGF0aCI6Ii82OTc3MzE5LzM2NDA2OTY0Mi1kNDc5YWEzMS1mYjU2LTQ0YTctYjllNC1kODNkYTExYjZlZmQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMTE0NDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJkMTUyMzRiYWVmMmY4YzBmM2Q4NzkwMjhhZTMxMWViOTA0M2Y3MGFkYjRhYjJiYjQ4YTI1NWZiYjBhMWRmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hQwQPx4Dfts6luIT2WbVJCiNFO3TMr91RGu0Khr3SO4)
> 
> issue still exist, when I goto the test, I can't get any response when I click any button

armv7 also?

2024-09-04 12:57 UTC, halx99 commented
> > > This test seems dead loop on android device: ![Screenshot_2024-09-04-00-46-21-107_org axmol cpp_tests](https://private-user-images.githubusercontent.com/6977319/364069642-d479aa31-fb56-44a7-b9e4-d83da11b6efd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTA1NzUsIm5iZiI6MTcyNTQ1MDI3NSwicGF0aCI6Ii82OTc3MzE5LzM2NDA2OTY0Mi1kNDc5YWEzMS1mYjU2LTQ0YTctYjllNC1kODNkYTExYjZlZmQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMTE0NDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJkMTUyMzRiYWVmMmY4YzBmM2Q4NzkwMjhhZTMxMWViOTA0M2Y3MGFkYjRhYjJiYjQ4YTI1NWZiYjBhMWRmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hQwQPx4Dfts6luIT2WbVJCiNFO3TMr91RGu0Khr3SO4)
> > 
> > 
> > issue still exist, when I goto the test, I can't get any response when I click any button
> 
> armv7 also?

Yes

2024-09-04 13:16 UTC, aismann commented
Can you try to reduce the sizes?
static float WID = 400;
    static float HIG = 600

WID is  also on renderline again

2024-09-05 05:36 UTC, aismann commented
@halx99 
Please review again. its all done and ready for merge

2024-09-06 00:54 UTC, halx99 approved these changes

2024-09-06 13:31 UTC, merged

2024-09-16 17:48 UTC, halx99 commented
@aismann does the folder https://github.com/axmolengine/axmol/tree/dev/extensions/DrawNodeEx/ can be deleted?